'use client';
import '@/styles/globals.css';
import React from 'react';
import Header from '@/components/common/Header';
import Footer from '@/components/common/Footer';

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html dir="ltr">
            <head>
                <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1, viewport-fit=cover"
                />
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <title>Next.js Razor Theme</title>
            </head>
            <body className="overflow-y-scroll bg-zinc-900">
                <div className="flex min-h-screen flex-col">
                    <header className="header">
                        <Header />
                    </header>
                    <main className="main relative flex-grow">{children}</main>
                    <footer className="footer">
                        <Footer />
                    </footer>
                </div>
            </body>
        </html>
    );
}
