'use client'
import '@/styles/globals.css';
import AddressBar from '@/ui/AddressBar';
import GlobalNav from './GlobalNav';
import Head from 'next/head';
import React, { Suspense, lazy } from 'react';
import RecommendedProducts from '@/components/recommendedProducts';
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

// import type { AppProps } from 'next/app'

// export default function App({ Component, pageProps }: AppProps) {
//     console.log('run here');
//   return <Component {...pageProps} />
// }


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
    console.log('nope run here instead')
  return (
    <html dir="ltr">
      <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
        <meta
            name="description"
            content="Generated by create next app"
        />
        <title>Next.js Razor Theme</title>
      </head>
      <body className="overflow-y-scroll bg-zinc-900">
        <div className="flex flex-col min-h-screen">
            <header className="header">
                <Header />
            </header>
            <main className="main relative flex-grow">{children}</main>
            <footer className="footer">
                <Footer />
            </footer>
        </div>
      </body>
    </html>
  );
}
