import Head from 'next/head';
import React, { Suspense, lazy } from 'react';
import RecommendedProducts from '@/components/recommendedProducts';
//const BrandSlider = lazy(() => import('@/components/brandSlider/BrandSlider'));

function Home() {
    return (
        <>
            <Head>
                <title>Razor Theme Next</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </>
    );
}

export default Home;
