import Head from "next/head";
import React from "react";
import Layout from "@/components/layout/Layout";
import BrandSlider from "@/components/brandSlider/BrandSlider";
import RecommendedProducts from "@/components/recommendedProducts";

function Home() {
    return (
        <>
            <Head>
                <title>Razor Theme Next</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <RecommendedProducts />
                <BrandSlider />
            </Layout>
        </>
    );
}

export default Home;
