import Head from "next/head";
import React, { Suspense, lazy } from "react";
import Layout from "@/components/layout/Layout";
import RecommendedProducts from "@/components/recommendedProducts";

const BrandSlider = lazy(() => import("@/components/brandSlider/BrandSlider"));

function wait(time: number) {
    return new Promise((resolve) => {
        setTimeout(resolve, time);
    });
}

function Home() {
    return (
        <>
            <Head>
                <title>Razor Theme Next</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <RecommendedProducts />
                <Suspense
                    fallback={
                        <p className="absolute inset-0 mx-auto container">
                            Loading...
                        </p>
                    }
                >
                    <BrandSlider />
                </Suspense>
            </Layout>
        </>
    );
}

export default Home;
