import Head from "next/head";
import React, { Suspense, lazy } from "react";
import Layout from "@/components/layout/Layout";
import BrandSlider from "@/components/brandSlider/BrandSlider";
import RecommendedProducts from "@/components/recommendedProducts";
import lazyload from "@/components/utils/lazyload";

const Exp = lazy(() => wait(12000).then(() => import("@/app/experimental")));
// const Exp = lazyload(() => {
//     import("@/app/experimental").then((module) => {
//         return { default: module.Experimental };
//     });
// });

function wait(time: number) {
    return new Promise((resolve) => {
        setTimeout(resolve, time);
    });
}

function Home() {
    return (
        <>
            <Head>
                <title>Razor Theme Next</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <RecommendedProducts />
                <BrandSlider />
                <Suspense fallback={<h4>Loading...</h4>}>
                    <Exp title="Title Data Test"></Exp>
                </Suspense>
            </Layout>
        </>
    );
}

export default Home;
